version: '3'

services:
  web:
    build: .
    container_name: machine_learning
    command: uvicorn main:app --host 0.0.0.0 --port 8080 --reload
    ports:
      - 8080:8080
    volumes:
      - .:/app